#!/usr/bin/env python3
"""Pack spec.json + main.py into the daemon's AuthoredOperator install shape.

    python3 pack.py > epn.diag.v1.json

The output is what POST /v1/operators/install accepts: {"spec": …,
"source_files": {"main.py": …}}. The manifests are GENERATED by the daemon from
the spec (RunnerManifests), never written here -- so this file cannot say one
thing and deploy another.
"""
import json
import os
import sys

here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(here, "spec.json"), encoding="utf-8") as f:
    spec = json.load(f)
with open(os.path.join(here, "main.py"), encoding="utf-8") as f:
    src = f.read()

json.dump({"spec": spec, "source_files": {"main.py": src}}, sys.stdout, indent=2)
sys.stdout.write("\n")
